FROM node:20.14

WORKDIR /frontend

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 5173

# CMD [ "tail", "-f", "/dev/null" ]

ENTRYPOINT ["npm"]
CMD ["run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]